name: krew-index CI

on: pull_request

jobs:
  build:
    name: Build and Tags
    runs-on: ubuntu-latest
    env:
      KREW_VERSION: v0.3.4
      GO111MODULE: on
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out PR branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # disable shallow clones

    - name: Fetch base branch
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/${GITHUB_BASE_REF}:refs/remotes/origin/${GITHUB_BASE_REF}

    - name: Install kubectl
      run: |
        set -euo pipefail
        sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kubectl
        sudo chmod +x /usr/bin/kubectl

    - name: Install krew
      run: |
        set -euo pipefail
        cd "$(mktemp -d)"
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew.{tar.gz,yaml}"
        tar zxvf krew.tar.gz
        ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz

    - name: Install validate-krew-manifest plugin
      run : |
        set -euo pipefail
        export GOBIN=$HOME/bin
        go get sigs.k8s.io/krew/cmd/validate-krew-manifest@${KREW_VERSION}

    - name: Validate updated plugin manifests
      run : |
        set -x
        set -euo pipefail
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        git diff --name-only --diff-filter=AM origin/${GITHUB_BASE_REF} ${{ github.sha }} -- plugins/ |
          tee /dev/stderr |
          xargs -I _ $HOME/bin/validate-krew-manifest -manifest _

