name: krew-index CI

on: pull_request

jobs:
  build:
    name: Validate plugin manifests
    runs-on: ubuntu-latest
    env:
      KREW_VERSION: v0.4.2
      GO111MODULE: on
    steps:

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Go module cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check out PR branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # disable shallow clones

    - name: Fetch base branch
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/${GITHUB_BASE_REF}:refs/remotes/origin/${GITHUB_BASE_REF}

    - name: Install kubectl
      run: |
        set -euo pipefail
        sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubectl
        sudo chmod +x /usr/bin/kubectl

    - name: Install krew
      run: |
        set -euo pipefail
        cd "$(mktemp -d)"
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew.{tar.gz,yaml}"
        tar zxvf krew.tar.gz
        ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz

    - name: Install validate-krew-manifest plugin
      run : |
        set -euo pipefail
        export GOBIN=$HOME/bin
        # TODO(corneliusweig): pin validator version after next release
        # go get sigs.k8s.io/krew/cmd/validate-krew-manifest@${KREW_VERSION}
        go get sigs.k8s.io/krew/cmd/validate-krew-manifest@b015efbdf40d4cce7e02b9e4e4805d373c40aa25

    - name: Validate updated plugin manifests
      run : |
        set -x
        set -euo pipefail
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        git diff --name-only --diff-filter=AM origin/${GITHUB_BASE_REF} ${{ github.sha }} -- plugins/ |
          tee /dev/stderr |
          xargs -I _ $HOME/bin/validate-krew-manifest -manifest _

